@echo off
set PIP=C:\Users\baraa\interactive-learning-platform\backend\.venv\Scripts\pip.exe

echo [1/7] peft...
%PIP% install peft --quiet
echo [2/7] librosa soundfile...
%PIP% install librosa soundfile --quiet
echo [3/7] python-Levenshtein openpyxl...
%PIP% install python-Levenshtein openpyxl --quiet
echo [4/7] gtts pydub...
%PIP% install gtts pydub --quiet
echo [5/7] phonemizer...
%PIP% install phonemizer --quiet
echo [6/7] speechbrain...
%PIP% install speechbrain --quiet
echo [7/7] huggingface_hub...
%PIP% install huggingface_hub --quiet

echo DONE — all ASR deps installed
