/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpecialistSignupRouteImport } from './routes/specialist-signup'
import { Route as SpecialistLoginRouteImport } from './routes/specialist-login'
import { Route as SpecialistRouteImport } from './routes/specialist'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SelectChildRouteImport } from './routes/select-child'
import { Route as ParentRouteImport } from './routes/parent'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LearnIndexRouteImport } from './routes/learn.index'
import { Route as LearnWordRouteImport } from './routes/learn.word'
import { Route as LearnVoiceRouteImport } from './routes/learn.voice'
import { Route as LearnTalkRouteImport } from './routes/learn.talk'
import { Route as LearnPictureRouteImport } from './routes/learn.picture'
import { Route as LearnExercisesRouteImport } from './routes/learn.exercises'

const SpecialistSignupRoute = SpecialistSignupRouteImport.update({
  id: '/specialist-signup',
  path: '/specialist-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecialistLoginRoute = SpecialistLoginRouteImport.update({
  id: '/specialist-login',
  path: '/specialist-login',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecialistRoute = SpecialistRouteImport.update({
  id: '/specialist',
  path: '/specialist',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectChildRoute = SelectChildRouteImport.update({
  id: '/select-child',
  path: '/select-child',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentRoute = ParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LearnRoute,
} as any)
const LearnWordRoute = LearnWordRouteImport.update({
  id: '/word',
  path: '/word',
  getParentRoute: () => LearnRoute,
} as any)
const LearnVoiceRoute = LearnVoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => LearnRoute,
} as any)
const LearnTalkRoute = LearnTalkRouteImport.update({
  id: '/talk',
  path: '/talk',
  getParentRoute: () => LearnRoute,
} as any)
const LearnPictureRoute = LearnPictureRouteImport.update({
  id: '/picture',
  path: '/picture',
  getParentRoute: () => LearnRoute,
} as any)
const LearnExercisesRoute = LearnExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => LearnRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/learn': typeof LearnRouteWithChildren
  '/login': typeof LoginRoute
  '/parent': typeof ParentRoute
  '/select-child': typeof SelectChildRoute
  '/signup': typeof SignupRoute
  '/specialist': typeof SpecialistRoute
  '/specialist-login': typeof SpecialistLoginRoute
  '/specialist-signup': typeof SpecialistSignupRoute
  '/learn/exercises': typeof LearnExercisesRoute
  '/learn/picture': typeof LearnPictureRoute
  '/learn/talk': typeof LearnTalkRoute
  '/learn/voice': typeof LearnVoiceRoute
  '/learn/word': typeof LearnWordRoute
  '/learn/': typeof LearnIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/parent': typeof ParentRoute
  '/select-child': typeof SelectChildRoute
  '/signup': typeof SignupRoute
  '/specialist': typeof SpecialistRoute
  '/specialist-login': typeof SpecialistLoginRoute
  '/specialist-signup': typeof SpecialistSignupRoute
  '/learn/exercises': typeof LearnExercisesRoute
  '/learn/picture': typeof LearnPictureRoute
  '/learn/talk': typeof LearnTalkRoute
  '/learn/voice': typeof LearnVoiceRoute
  '/learn/word': typeof LearnWordRoute
  '/learn': typeof LearnIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/learn': typeof LearnRouteWithChildren
  '/login': typeof LoginRoute
  '/parent': typeof ParentRoute
  '/select-child': typeof SelectChildRoute
  '/signup': typeof SignupRoute
  '/specialist': typeof SpecialistRoute
  '/specialist-login': typeof SpecialistLoginRoute
  '/specialist-signup': typeof SpecialistSignupRoute
  '/learn/exercises': typeof LearnExercisesRoute
  '/learn/picture': typeof LearnPictureRoute
  '/learn/talk': typeof LearnTalkRoute
  '/learn/voice': typeof LearnVoiceRoute
  '/learn/word': typeof LearnWordRoute
  '/learn/': typeof LearnIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/learn'
    | '/login'
    | '/parent'
    | '/select-child'
    | '/signup'
    | '/specialist'
    | '/specialist-login'
    | '/specialist-signup'
    | '/learn/exercises'
    | '/learn/picture'
    | '/learn/talk'
    | '/learn/voice'
    | '/learn/word'
    | '/learn/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/parent'
    | '/select-child'
    | '/signup'
    | '/specialist'
    | '/specialist-login'
    | '/specialist-signup'
    | '/learn/exercises'
    | '/learn/picture'
    | '/learn/talk'
    | '/learn/voice'
    | '/learn/word'
    | '/learn'
  id:
    | '__root__'
    | '/'
    | '/learn'
    | '/login'
    | '/parent'
    | '/select-child'
    | '/signup'
    | '/specialist'
    | '/specialist-login'
    | '/specialist-signup'
    | '/learn/exercises'
    | '/learn/picture'
    | '/learn/talk'
    | '/learn/voice'
    | '/learn/word'
    | '/learn/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LearnRoute: typeof LearnRouteWithChildren
  LoginRoute: typeof LoginRoute
  ParentRoute: typeof ParentRoute
  SelectChildRoute: typeof SelectChildRoute
  SignupRoute: typeof SignupRoute
  SpecialistRoute: typeof SpecialistRoute
  SpecialistLoginRoute: typeof SpecialistLoginRoute
  SpecialistSignupRoute: typeof SpecialistSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/specialist-signup': {
      id: '/specialist-signup'
      path: '/specialist-signup'
      fullPath: '/specialist-signup'
      preLoaderRoute: typeof SpecialistSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specialist-login': {
      id: '/specialist-login'
      path: '/specialist-login'
      fullPath: '/specialist-login'
      preLoaderRoute: typeof SpecialistLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specialist': {
      id: '/specialist'
      path: '/specialist'
      fullPath: '/specialist'
      preLoaderRoute: typeof SpecialistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-child': {
      id: '/select-child'
      path: '/select-child'
      fullPath: '/select-child'
      preLoaderRoute: typeof SelectChildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent': {
      id: '/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof ParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/word': {
      id: '/learn/word'
      path: '/word'
      fullPath: '/learn/word'
      preLoaderRoute: typeof LearnWordRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/voice': {
      id: '/learn/voice'
      path: '/voice'
      fullPath: '/learn/voice'
      preLoaderRoute: typeof LearnVoiceRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/talk': {
      id: '/learn/talk'
      path: '/talk'
      fullPath: '/learn/talk'
      preLoaderRoute: typeof LearnTalkRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/picture': {
      id: '/learn/picture'
      path: '/picture'
      fullPath: '/learn/picture'
      preLoaderRoute: typeof LearnPictureRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/exercises': {
      id: '/learn/exercises'
      path: '/exercises'
      fullPath: '/learn/exercises'
      preLoaderRoute: typeof LearnExercisesRouteImport
      parentRoute: typeof LearnRoute
    }
  }
}

interface LearnRouteChildren {
  LearnExercisesRoute: typeof LearnExercisesRoute
  LearnPictureRoute: typeof LearnPictureRoute
  LearnTalkRoute: typeof LearnTalkRoute
  LearnVoiceRoute: typeof LearnVoiceRoute
  LearnWordRoute: typeof LearnWordRoute
  LearnIndexRoute: typeof LearnIndexRoute
}

const LearnRouteChildren: LearnRouteChildren = {
  LearnExercisesRoute: LearnExercisesRoute,
  LearnPictureRoute: LearnPictureRoute,
  LearnTalkRoute: LearnTalkRoute,
  LearnVoiceRoute: LearnVoiceRoute,
  LearnWordRoute: LearnWordRoute,
  LearnIndexRoute: LearnIndexRoute,
}

const LearnRouteWithChildren = LearnRoute._addFileChildren(LearnRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LearnRoute: LearnRouteWithChildren,
  LoginRoute: LoginRoute,
  ParentRoute: ParentRoute,
  SelectChildRoute: SelectChildRoute,
  SignupRoute: SignupRoute,
  SpecialistRoute: SpecialistRoute,
  SpecialistLoginRoute: SpecialistLoginRoute,
  SpecialistSignupRoute: SpecialistSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
